config/routes.rb
GoalSetter::Application.routes.draw do
  resources :users do
    member do
      get "edit_goal"
      put "update_goal"
      post "create_goal"
      delete "destroy_goal"
    end
  end

  resource :session

  root to: "session#new"
end

app/models/goal.rb
class Goal < ActiveRecord::Base
  attr_accessible :title, :user_id, :public
  validates :title, :user_id, :presence => true
  validates :public, :inclusion => { :in => [true, false] }

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :password, :token, :username

  validates :username, :password, :presence => true
  validates :password, :length => { :minimum => 6 }



  def reset_token
    self.token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include ApplicationHelper
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController

  def create
    @goal = current_user.goals.new(params[:goal])
    create_and_redirect_for!(@goal, user_url(current_user))
  end

  def edit
    @goal = Goal.find(params[:goal][:id])
    redirect_to current_user
  end

  def update
    @goal = Goal.find(params[:goal][:id])
    if @goal.update_attributes(params[:goal])
      
    else
    end

  end

  def destroy
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_username_and_password(
      params[:user][:username],
      params[:user][:password]
    )

    create_and_redirect_for!(@user)
  end

  def destroy
    session[:token] = nil
    current_user.reset_token if logged_in?
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, only: [:show]
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])

    create_and_redirect_for!(@user)
  end

  def show
    fail
    @user = User.find(params[:id])
  end

  def create_goal
    @goal = current_user.goals.new(params[:goal])
    create_and_redirect_for!(@goal, user_url(current_user))
  end

  def edit_goal
    @goal = Goal.find(params[:goal][:id])
    render :show
  end

  def update_goal
    @goal = Goal.find(params[:goal][:id])
    if @goal.update_attributes(params[:goal])
      redirect_to current_user
    else
      flash[:errors] = @goal.errors.full_messages
      render :show
    end

  end

  def destroy_goal
    @goal = Goal.find(params[:goal][:id])
    @goal.delete!
    render :show
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    return nil unless session[:token]
    @current_user ||= User.find_by_token(session[:token])
  end

  def logged_in?
    !!current_user
  end

  def authenticate
    redirect_to new_session_url unless logged_in?
  end

  def create_and_redirect_for!(model, redirect_url = nil)
    if model && model.save
      session[:token] = model.reset_token if model.class == User
      redirect_to  redirect_url || current_user #all info on the show page
    else
      if model.nil? #implies no user found
        flash[:errors] =  ["Username or Password is wrong"]
      else
        flash[:errors] =  model.errors.full_messages
        render :new
      end
    end
  end

end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/_form.html.erb
<h2><%= action == "new_goal" ? "new goal" : "edit goal" %></h2>
<p>
  <form action=<%= "#{action}_url" method="post">>
    <%= render partial: "layouts/authenticity" %>

    <% if action == "edit_goal" %>
      <input type="hidden" name="_method" value="put">
    <% end %>

    <p>
    <label>Title
      <input type="text" name="goal[title]" value="<%= @goal.title %>">
    </label>
    </p>

    <p>
      <label>Type
        <%# need to re-write so that a variable is declared that does checked for the radio buttons %>
        <label>
          <input type="radio" name="goal[is_public]" value="true"
            <%= "checked" if !!@goal.is_public %>>
            Public
          </label>


        <label>
        <input type="radio" name="goal[is_public]" value="true"
          <%= "checked" if !@goal.is_public %>>
          Private
        </label>
      </p>


    <input >

</p>

app/views/layouts/_errors.html.erb
<% if flash[:errors] && !flash[:errors].empty? %>
  <% flash[:errors].each do |error| %>
	 <%= error %> <br />
	<% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>To Do</title>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <%= render :partial => "layouts/errors" %>

<% if logged_in? %>
  <%= current_user.username %>
  <%= button_to "Sign Out", session_url, :method => :delete %>
<% else %>
  <%= link_to "Sign In", new_session_url %>
  <%= link_to "Sign Up", new_user_url %>
<% end %>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h2>Create New User</h2>



<form action="/users" method="post" accept-charset="utf-8">
  <%= render :partial => "layouts/authenticity" %>

  <label for="username">Username</label>
  <input type="text" name="user[username]" value="" id="username">

  <label for="password">Password</label>
  <input type="password" name="user[password]" value="" id="password">

  <p><input type="submit" value="Sign Up"></p>
</form>

app/views/users/show.html.erb
<h1>User show<h1>
<% action = params[:action] %>